baseURL = "https://skaymakca.github.io/pub/"
languageCode = "en-us"
title = "Pub"

[params]
  description = "Central publishing hub for project docs and reports"

[markup.goldmark.renderer]
  unsafe = true
  hardWraps = true

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 2
  [[menu.main]]
    name = "Briefs"
    url = "/briefs/"
    weight = 3
  [[menu.main]]
    name = "Reports"
    url = "/reports/"
    weight = 4
